source 'https://rubygems.org'

# Ruby version - using 3.1.4 for Apple Silicon compatibility
ruby '~> 3.1.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.0'

# Use sqlite3 as the database for Active Record (simpler for learning)
gem 'sqlite3', '~> 1.4'

# Use Puma as the app server
gem 'puma', '~> 5.0'

# Logger gem for Ruby 2.6 compatibility
gem 'logger'

# CORS support for cross-origin requests
gem 'rack-cors'

# Build JSON APIs with ease
gem 'jbuilder'

# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'pry'
end

group :development do
  # Speed up commands on slow machines / big apps
  gem 'spring'
end

